pipeline {
    agent any

    stages {
        stage('Clone Code') {
            steps {
                git branch: 'main', url: 'https://github.com/<your-username>/2tier-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("flask-backend")
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withDockerRegistry([ credentialsId: 'dockerhub-token', url: '' ]) {
                    sh 'docker tag flask-backend <your-dockerhub-username>/flask-backend:latest'
                    sh 'docker push <your-dockerhub-username>/flask-backend:latest'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'helm upgrade --install two-tier-app helm-chart/'
            }
        }
    }
}
