# helm-chart/values.yaml

replicaCount: 1

image:
  repository: devpraveens/2tire-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""

resources: {}
