apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: devpraveens/flask-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: password
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: testdb
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
